
Gui, Pneumonie:Color, 0xffffff
Gui, Pneumonie:Add, Text, x30 y20 w90 h20 +Center, Audi
Gui, Pneumonie:Add, Button, x5 y80 w65 h20, Einfügen
Gui, Pneumonie:Add, Button, x5 y155 w65 h20, Einfügen
Gui, Pneumonie:Add, Checkbox, x135 y85 w75 h15 +Right, Zustand
Gui, Pneumonie:Add, Checkbox, x90 y160 w120 h15 +Right, Vorbesitzer
Gui, Pneumonie:Add, Edit, x235 y85 w395 h50, 
Gui, Pneumonie:Add, Edit, x235 y160 w395 h55, 
Gui, Pneumonie:Add, Button, x165 y260 w70 h35, Alle einfügen
Gui, Pneumonie:Add, Button, x270 y260 w70 h35, Abbrechen
Gui, Pneumonie:Add, Button, x380 y260 w70 h35 gLabel, Hauptmenü
Gui, Pneumonie:Show, w702 h339, Audi
return


Label:
Run, % A_GuiControl ".ahk" ;Endung .ahk anhängen

AudiGuiClose:
ExitApp
; This Gui is generated by X-GUI Creator