
Gui, Add, Tab, x0 y0 w480 h380, Lunge|Abdomen|Gehirn|Herz|Extremitäten|Verletzungen|Brüche|
Gui, Tab, 1, 1
Gui, Add, Button, x10 y40 w70 h20 gPneumonie, Pneumonie


;gPneumonie:
;run, "C:\Users\Baum\Desktop\Moodle Arbeit\Arbeit\Autohotkeys\Briefe\Pneumonie.ahk"
;return

Gui, Show, w483 h383, New GUI Window
return


Pneumonie:
Run, %A_ScriptDir%\Krankheiten\Pneumonie.ahk ;
return

GuiClose:
ExitApp
; This Gui is generated by X-GUI Creator

