
;~ This Gui is generated by X-GuiCreator (___x@___)
Gui, Font, s10, MS Shell Dlg
Gui, Color, F0F0F0, FFFFFF
Gui, Add, Tab2, x30 y20 w340 h285,Item1|Item2
Gui, Tab,1,1
Gui, Add, ListBox, x150 y95 w150 h52,ListBox
Gui, Add, Button, x52 y90 w90 h30 , Pneumonie
Gui, Tab,2,1
Gui, Add, ListBox, x135 y110 w160 h52,ListBox
Gui, Add, ListBox, x140 y200 w160 h52,ListBox
Gui, Tab
Gui, Add, ListBox, x120 y340 w150 h52,ListBox
Gui, Show, w500 h500, 
Return

GuiClose:
ExitApp